[
build
]
  functions = "functions"

[
context.production
]
  branch = "main"  # This sets the production branch to main

[[
redirects
]]
  from = "/badge/*"
  to = "/.netlify/functions/badge/:splat"
  status = 200
  force = true
